# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
# Mod Properties
mod_version=1.0
maven_group=com.campersamu
archives_base_name=chatheads

# Dependencies
# check this on https://modmuss50.me/fabric.html
kaleido_version=0.3.3+1.3.2
papi_version=2.1.4+1.20.1
polymer_version=0.5.9+1.20.1
